# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_batteries_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='db_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
