# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_batteries_app', '0002_auto_20170927_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='id',
        ),
    ]
